"use client";

import PageTransition from "../components/PageTransition";
import Disclaimer from "../components/Disclaimer";

export default function AboutPage() {
  return (
    <PageTransition>
      <div className="flex-grow pt-28 md:pt-32 pb-16 px-5 sm:px-8 md:px-10 lg:px-16 max-w-3xl mx-auto w-full space-y-12">
        {/* Header */}
        <div className="space-y-4">
          <h1 className="font-heading text-3xl md:text-4xl font-semibold text-text-primary tracking-tight">
            About Z-Combinator
          </h1>
          <p className="text-text-secondary text-base md:text-lg leading-relaxed">
            Z-Combinator is a structured evaluation tool for startup ideas. It applies frameworks from Y Combinator, Andreessen Horowitz, and NFX to give you cited, dimension-level feedback on your idea -- not a verdict on whether it will succeed.
          </p>
        </div>

        {/* What Z-Combinator Is / Is Not Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-4">
          <div className="space-y-4">
            <h2 className="font-heading text-xl font-semibold text-text-primary border-b border-border pb-2">
              What Z-Combinator Is
            </h2>
            <ul className="space-y-3 text-text-secondary text-sm sm:text-base leading-relaxed">
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>A framework-application tool, not an oracle</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>Grounded in retrieved framework excerpts, not unguided LLM opinion</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>A starting point for structured thinking, not a substitute for mentors or advisors</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>Free to use, no sign-up or account required</span>
              </li>
            </ul>
          </div>

          <div className="space-y-4">
            <h2 className="font-heading text-xl font-semibold text-text-primary border-b border-border pb-2">
              What Z-Combinator Is Not
            </h2>
            <ul className="space-y-3 text-text-secondary text-sm sm:text-base leading-relaxed">
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>Not investment, financial, legal, or business advice</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>Not a prediction of whether your idea will succeed in the market</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>Not a replacement for talking to real potential customers</span>
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none text-text-primary">—</span>
                <span>Not a storage service -- your ideas are processed in real time and immediately discarded</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Detailed Legal Disclaimer Card */}
        <div
          className="rounded-2xl border-2 p-6 md:p-8 bg-surface space-y-3 shadow-sm"
          style={{ borderColor: "var(--color-border-strong)" }}
        >
          <h3 className="font-heading text-lg font-semibold text-text-primary uppercase tracking-wider text-score-low">
            Legal Disclaimer
          </h3>
          <p className="text-text-secondary text-xs sm:text-sm leading-relaxed">
            Z-Combinator is provided on an as-is basis. The scores, valuations, suggestions, and justifications generated by this tool reflect the mechanical application of publicly available startup accelerator frameworks to your text inputs. They do not constitute professional advice, endorsement, or consulting of any kind.
          </p>
          <p className="text-text-secondary text-xs sm:text-sm leading-relaxed">
            No warranties or guarantees, express or implied, are made regarding the accuracy, completeness, viability, or applicability of any report to your specific situation or jurisdiction. Do not make material business, financial, or legal decisions based solely on Z-Combinator output. Always consult qualified professionals before taking action on any evaluation.
          </p>
        </div>

        {/* Contact info */}
        <div className="text-center pt-4 border-t border-border">
          <p className="text-text-secondary text-sm font-body">
            Questions or feedback? Reach us at{" "}
            <a
              href="mailto:ping@z-combinator.com"
              className="text-text-primary font-medium hover:underline underline-offset-4"
            >
              ping@z-combinator.com
            </a>
          </p>
        </div>
      </div>
      <Disclaimer />
    </PageTransition>
  );
}
